MongoDB:
  host: localhost
  port: 27017
  database: dota2
  collection:
    ranked-collections: rankedGames
    public-collections: publicGames
    professional-collections: professionalGames
    match-result-collections: matchResults
